[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "rust_lib.rs"
crate-type = ["staticlib", "lib"]

[[bin]]
name = "rust_lib_main"
path = "main.rs"

[[test]]
name = "rust_lib_test"
path = "test.rs"

[[example]]
name = "rust_lib_example"
path = "example.rs"